### ISSUE TITLE
单行居中多行居左布局

### ISSUE THREAD

**Issue by simonyouth** [simonyouth/Blog#1]
实现居中自适应居中，当元素不满一行时居中对齐，超过一行看似居左对齐

多行时：
![多行](https://user-images.githubusercontent.com/27126241/60422982-b5d40100-9c1f-11e9-94d6-b8b1d89deed9.png)

一行：
![adaptive-center-one](https://user-images.githubusercontent.com/27126241/60423234-54606200-9c20-11e9-8fea-1e7af98d0323.png)

原理是父元素中使用`text-align:center`使子内联元素居中。一级子元素是内联元素，其子元素将其撑满，不满一行时显示效果是居中。超过一行时一级子元素的width等于其父元素的width，显示效果居左。

那么，**块级元素需要使用`margin: 0 auto`来实现一样的效果**。

```html
<body>
  <div class="container">
    <div class="flex-box">
      <div class="item"></div>
      <div class="item"></div>
      <div class="item"></div>
    </div>
  </div>
</div>
</body>
```
```css
body {
  width: 100%;
}

.container {
  text-align: center;
}

.flex-box {
  display: inline-flex;
  flex-wrap: wrap;
}

.item {
  margin-top: 10px;
  margin-right: 10px;
  width: 100px;
  height: 100px;
  border: 1px solid forestgreen;
}
```
